/*
  # Add vector search capabilities to tasks table

  1. Extensions
    - Enable pgvector extension for vector similarity search

  2. Changes to tasks table
    - Add embedding column (vector type with 384 dimensions for gte-small model)
    - Create index on embedding column for fast similarity search

  3. Functions
    - Create function to search tasks by vector similarity

  4. Important Notes
    - Embeddings will be generated by Edge Function using Supabase AI
    - Vector similarity search uses cosine distance
    - Only returns results with similarity > 0.7 (distance < 0.3)
*/

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column to tasks table
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'tasks' AND column_name = 'embedding'
  ) THEN
    ALTER TABLE tasks ADD COLUMN embedding vector(384);
  END IF;
END $$;

-- Create index for vector similarity search
CREATE INDEX IF NOT EXISTS idx_tasks_embedding ON tasks USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Create function to search tasks by similarity
CREATE OR REPLACE FUNCTION search_tasks_by_similarity(
  query_embedding vector(384),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 2,
  user_id_filter uuid DEFAULT NULL
)
RETURNS TABLE (
  id uuid,
  title text,
  priority text,
  status text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    t.id,
    t.title,
    t.priority,
    t.status,
    1 - (t.embedding <=> query_embedding) AS similarity
  FROM tasks t
  WHERE 
    t.embedding IS NOT NULL
    AND (user_id_filter IS NULL OR t.user_id = user_id_filter)
    AND 1 - (t.embedding <=> query_embedding) >= match_threshold
  ORDER BY t.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;
